name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^4.0.0
  google_sign_in: ^7.1.1
  firebase_auth: ^6.0.0
  get_storage: ^2.1.1
  path_provider: ^2.1.1
  lottie: ^3.3.1
  introduction_screen: ^3.1.17
  avatar_glow: ^2.0.1
  emoji_picker_flutter: ^4.3.0
  cloud_firestore: ^6.0.0
  intl: ^0.18.1
  image_picker: 1.1.2
  permission_handler: ^11.0.1
  animated_bottom_navigation_bar: ^1.3.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/chateo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  assets:
    - assets/lottie/
    - assets/logo/
  uses-material-design: true
